site_name: UCLCSSA新生手册
theme:
  name: 'material'
  language: 'zh'
  logo: 
    icon: 'account_balance'
  palette:
    primary: 'red'
    accent: 'deep orange'
  font:
    text: 'Noto Sans SC'
  feature:
    tabs: true
markdown_extensions:
  - admonition
extra:
  social:
    - type: 'facebook'
      link: 'https://www.facebook.com/691076590989125/'
    - type: 'weibo'
      link: 'https://www.weibo.com/cssaucl/'
    - type: 'github'
      link: 'https://github.com/uclcssa'