site_name: UCLCSSA新生手册
theme:
  name: 'material'
  language: 'zh'
  logo: 
    icon: 'account_balance'
  palette:
    primary: 'red'
    accent: 'deep orange'
  font:
    text: 'Noto Sans SC'
  feature:
    tabs: true

copyright: 'Copyright &copy; 2004 - 2019 UCLCSSA'

markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.def_list
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material

extra_css:
  - 'stylesheets/style.css'

extra:
  social:
    - type: 'link'
      link: 'https://www.uclcssa.org/'
    - type: 'facebook'
      link: 'https://www.facebook.com/691076590989125/'
    - type: 'weibo'
      link: 'https://www.weibo.com/cssaucl/'
    - type: 'github'
      link: 'https://github.com/uclcssa'